services:
  app:
    build: .
    container_name: taskmanager-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/taskmanager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=taskmanager
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      # Force TCP to avoid socket confusion; allow a real warm-up window
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_DATASOURCES_0_NAME=Prometheus
      - GF_DATASOURCES_0_TYPE=prometheus
      - GF_DATASOURCES_0_URL=http://prometheus:9090 
      - GF_DATASOURCES_0_ACCESS=proxy
      - GF_DATASOURCES_0_IS_DEFAULT=true
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  mysql-data:
  grafana-storage: {}
