
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/taskmanager?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl.auto=update

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=taskmanager
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
