
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/taskmanager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=taskmanager
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
