name: Java CI with Gradle

on:
  push:
    branches: [ main, develop ] # Triggers on push to main or develop
  pull_request:
    branches: [ main, develop ] # Triggers on pull requests

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write # This is needed for the jacoco-report action to comment on a PR

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Run all tests and create combined coverage report
        run: ./gradlew clean jacocoTestReport --info --stacktrace

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
